name: Build notes
on: push

jobs:
  build_typst_notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build the notes
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            notes.typ
      - name: Build the slides
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            presentation.typ
      - name: Upload the PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: |
            notes.pdf
            presentation.pdf
      - name: Delete old release
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: latest
          assets: '*.*'
          fail-if-no-assets: false
          fail-if-no-release: false
      - name: Release to main
        uses: softprops/action-gh-release@v1
        with:
          files: |
            notes.pdf
            presentation.pdf
          tag_name: latest
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }}"
          files: |
            notes.pdf
            presentation.pdf
      - name: Wrap up artifacts
        run: |
          mkdir build
          mv *.pdf build/
      - name: Upload to GH pages
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build
  deploy_pages:
    runs-on: ubuntu-latest
    needs: build_typst_notes
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GH Pages
        id: deployment
        uses: actions/deploy-pages@v4
